name: .NET Publish Nuget

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Set VERSION variable from tag
      run: |
        echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
        echo ${VERSION}
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c RELEASE
    - name: Test
      run: dotnet test Tests/Nuages.Localization.Tests/Nuages.Localization.Tests.csproj -c RELEASE
    - name: Pack
      run: dotnet pack Nuages.Localization/Nuages.Localization.csproj --output ./nupkgs -p:PackageVersion=${VERSION} -c RELEASE
    - name: Push
      run: dotnet nuget push ./nupkgs/*.nupkg -k ${{ secrets.NUGETKEY }} -s nuget.org
      
